version: "3.3"

services:
  loki:
    image: grafana/loki:latest
    container_name: master-loki
    restart: unless-stopped
    ports:
    - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: master-grafana
    restart: unless-stopped
    volumes:
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
    - 3000:3000