version: "3.8"

networks:
  loki:
  traefik-proxy:
    external: true

volumes:
  grafana-data:
  loki-data:

services:
  grafana:
    image: grafana/grafana:9.3.2
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: login
    networks:
      - loki
#    depends_on:
#      - loki
#    labels:
#      - traefik.enable=true
#      - traefik.http.services.loki.loadbalancer.server.port=3000
#      - traefik.http.routers.loki.rule=Host(`loki.example.com`)
#      - traefik.http.routers.loki.tls.certresolver=le
#      - traefik.http.routers.loki.entrypoints=websecure
#      - traefik.docker.network=traefik-proxy

  loki:
    image: grafana/loki:2.7.0
    container_name: loki
    restart: unless-stopped
    volumes:
      #- ./loki-config.yaml:/mnt/config/loki-config.yml
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    networks:
      - loki
    #command: -config.file=/mnt/config/loki-config.yml
    command: -config.file=/etc/loki/loki-config.yaml

#  promtail_docker:
#          #docker run --name promtail -d -v /var/log:/var/log --link loki grafana/promtail:2.7.0
#    image: grafana/promtail:2.7.0
#    container_name: promtail
#    volumes: 
#      - ./promtail-config.yaml:/etc/promtail/config.yaml
#      - /var/log:/var/log
#    command: -config.file=/etc/promtail/config.yaml
#    networks:
#      - loki


## activar cualquiera de los 2 servidores

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"  
    ports:
      - 81:80
    networks:
    - loki  

  hello-world:
    container_name:  hello-world
    image: kerwood/hello-world
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
    ports:
      - "80:80"
    networks:
      - loki  