version: "3.3"
services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    container_name: "swagger-editor"
    ports:
      - "8081:8080"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8082:8080"
    volumes:
      #- ./swagger/openapi.json:/openapi.json
      - ./swagger:/usr/share/nginx/html/swagger
      #- ./swagger/:/
    environment:
      #SWAGGER_JSON: /openapi.json
      # API_URL: ""
      # API_URL: doc/openapi.yaml
      URLS: "[{ url: \"swagger/openapi.json\", name: \"UserManagement\" },
                    { url: \"swagger/Counters_API.json\", name: \"CheckServer\" },
                ]"
      

  swagger-api:
    image: danielgtaylor/apisprout
    container_name: "swagger-api"
    ports:
      - "8083:8000"
    volumes:
      - ./swagger/openapi.json:/openapi.json
    command: /openapi.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    image: nginx:mainline-alpine
    container_name: "swagger-nginx"
    ports:
      - "8084:8084"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api

networks:
  swagger_link:


volumes:
    dbdata: