version: "3.8"

volumes:
  grafana-data:
  prometheus-data:
  loki-data:

services:

  loki:
    image: grafana/loki:2.7.0
    container_name: master_loki
    restart: unless-stopped
    volumes:
      - ./loki-config.yaml:/etc/loki/loki-config.yaml
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yaml

  grafana:
    image: grafana/grafana:8.0.6
    container_name: master_grafana
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: login

  prometheus:
      image: prom/prometheus:v2.30.0
      container_name: master_prometheus
      restart: unless-stopped
      volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      ports:
        - 9090:9090
      command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=5d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.enable-lifecycle'