version: '3'

volumes:
  postgres_data:
      driver: local
  datadb:
  pg_admin:

services:      
#WSO2
  pgadmin:
    image: dpage/pgadmin4:7.3
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: jose.casas@blocknitive.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pg_admin:/var/lib/pgadmin
      
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_ROOT_USER:     postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB:       WSO2AM_DB
      POSTGRES_USER:     wso2carbon
      POSTGRES_PASSWORD: wso2carbon
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./db/postgres/postgresql_share.sql:/var/lib/postgresql/postgresql_share.sql
      - ./db/postgres/postgresql-mb.sql:/var/lib/postgresql/postgresql-mb.sql
      - ./db/postgres/postgresql.sql:/var/lib/postgresql/postgresql.sql
      - ./db/postgres/postgresql_share.sql:/docker-entrypoint-initdb.d/postgresql_share.sql
      - ./db/postgres/postgresql-mb.sql:/docker-entrypoint-initdb.d/postgresql-mb.sql
      - ./db/postgres/postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
  api-manager:
    build: ./
    container_name: api-manager
    labels:
      name: wso2
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z","localhost", "9443"]
      interval: 10s
      start_period: 180s
      retries: 20
    volumes: 
      - ./conf/deployment.toml:/home/wso2carbon/wso2am-4.2.0/repository/conf/deployment.toml
      - ./db/connector/postgresql-42.6.0.jar:/home/wso2carbon/wso2am-4.2.0/repository/components/lib/postgresql-42.6.0.jar
      - ./db/connector/postgresql-42.6.0.jar:/home/wso2carbon/wso2am-4.2.0/repository/components/dropins/postgresql-42.6.0.jar
      #- datadb:/home/wso2carbon/wso2am-4.2.0/repository/database
      #- ./conf/master-datasources.xml:/home/wso2carbon/wso2am-4.2.0/repository/conf/datasources/master-datasources.xml
                                        
    ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"

#KEYCLOAK
  #keycloak-db:
  #  image: postgres:14-alpine
  #  container_name: keycloak-db
  #  restart: always
  #  volumes: 
  #    - postgres_data:/var/lib/postgresql/data
  #  ports:
  #    - "25432:5432"
  #  environment:
  #    POSTGRES_DB:       keycloak
  #    POSTGRES_USER:     keycloak
  #    POSTGRES_PASSWORD: password

  #keycloak:
  #  #image: quay.io/keycloak/keycloak:21.1.1
  #  #image: jboss/keycloak:9.0.3
  #  image: quay.io/keycloak/keycloak:19.0
  #  container_name: keycloak
  #  restart: always
  #  depends_on:
  #    - keycloak-db
  #  command: start-dev
  #  ports:
  #    - "8180:8080"
  #  environment:
  #    DB_VENDOR:   POSTGRES
  #    DB_ADDR:     keycloak-db
  #    DB_PORT:     5432
  #    DB_DATABASE: keycloak
  #    DB_USER:     keycloak
  #    DB_SCHEMA:   public
  #    DB_PASSWORD: password
  #    KEYCLOAK_ADMIN:     admin
  #    KEYCLOAK_ADMIN_PASSWORD: admin