version: "3.3"

volumes:
  grafana-data:
  prometheus-data:    
  loki-data:

services:
  loki:
    image: grafana/loki:latest
    container_name: master-loki
    restart: unless-stopped
    volumes:
    - loki-data:/loki
    ports:
    - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: master-grafana
    restart: unless-stopped
    volumes:
    - grafana-data:/var/lib/grafana
    - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
    - 3000:3000

  prometheus:
    image: prom/prometheus:latest
    container_name: master-prometheus
    restart: unless-stopped
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-data:/prometheus
    ports:
    - 9090:9090
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention.time=90d'
    - '--storage.tsdb.retention.size=100GB'
    - '--web.enable-lifecycle'
