global:
  scrape_interval:     30s # El intervalo en el que se traerá las métricas
  evaluation_interval: 30s # Evaluará las reglas cada 30 segundos, por defecto es cada minuto

scrape_configs:

  - job_name: 'servers-dev'
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{__name__=~".+"}'
    static_configs:
      - targets: [ '192.168.56.102:9090']  # DEV
        labels:
          pais: AR
          entorno: DEV
          cliente: caosbinario
          hostname: dev-caosbinario-ar
      
